name: Make a page release.

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.1'
        bundler-cache: true

    - name: Install dependencies
      run: |
        bundle install

    - name: Build site with Jekyll
      run: bundle exec jekyll build

    - name: Upload built site artifact
      uses: actions/upload-artifact@v4
      with:
        name: _site
        path: _site
